ci: test release workflow
tailcallhq/tailcall pull request #1982
Opened 2024-05-17 11:46 UTC by mehulmathur16

**Summary:**  
This PR adds a workflow for testing release build. This workflow will only be triggered if `ci: test release` label is added to a PR.

**Issue Reference(s):**  
Fixes #... _(Replace "..." with the issue number)_

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [ ] I have performed a self-review of my code.
- [ ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

2024-05-17 12:14 UTC, meskill requested changes

2024-05-17 12:14 UTC, meskill commented on .github/workflows/test_release.yml
> +      GITHUB_TOKEN: ${{secrets.GITHUBTOKEN}}
why do we need these permissions and env?

I don't think we doing anything here except for testing that build is successful

2024-05-17 12:14 UTC, meskill commented on .github/workflows/test_release.yml
> +            ext: ".exe"
it'll be hard to maintain this list in multiple places.

We should consider reusing strategy matrix. Probably with the help of https://github.com/druzsan/setup-matrix and https://docs.github.com/en/actions/using-workflows/reusing-workflows

2024-05-22 06:55 UTC, tusharmath commented
Moving to draft, until the comments are resolved/answered.

2024-05-29 10:02 UTC, closed without merging