fix: enchance request_handler.rs and added cors integration tests
tailcallhq/tailcall pull request #1989
Opened 2024-05-20 08:03 UTC by varshith257

**Summary:**  
_Briefly describe the changes made in this PR._

**Issue Reference(s):**  
Fixes #... _(Replace "..." with the issue number)_

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [ ] I have performed a self-review of my code.
- [ ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

2024-05-20 08:13 UTC, varshith257 commented
@tusharmath I think it's ready for your review. If any suggestions or modifications needed, I am ready to incorporate them

2024-05-22 12:32 UTC, tusharmath commented on tests/core/cors.rs
> +    }
Can we write an integration test like this — https://tailcall.run/developers/integration-testing/

2024-06-11 09:56 UTC, varshith257 commented
Any suggestions on why tests are failing?

2024-06-11 10:47 UTC, tusharmath commented
You had to run `cargo test` locally to generate the snapshots.

2024-06-11 10:48 UTC, tusharmath commented on src/core/http/request_handler.rs
>  }
These changes doesn't seem to be doing much. Can we revert it to the one it was in main?

2024-06-11 12:19 UTC, varshith257 commented
@tusharmath Any tip for trying to get optimise the request_handler.rs file from a long ?

2024-06-12 05:46 UTC, tusharmath approved these changes

2024-06-12 05:47 UTC, tusharmath commented on tests/execution/test-cors-tailcall-run.md
> +      access-control-allow-headers: "*"
Let's add a few more tests, with different methods, origin, and header settings. To ensure that our logic is working properly.

2024-06-12 05:47 UTC, tusharmath commented on tests/execution/test-cors-tailcall-run.md
> +- method: OPTIONS
If cors is enabled we need to try to make requests with `GET` and `POST` methods also.

2024-06-12 05:48 UTC, tusharmath requested changes
Fix review comments. Whenever completed, please mark it as ready to review.

2024-06-12 12:50 UTC, varshith257 commented
I am unable to run `cargo test` to generate snapshots. This emitting lot of errors

2024-06-21 10:31 UTC, meskill requested changes

2024-06-21 10:31 UTC, meskill commented on tests/execution/test-cors-tailcall-run.md
> +      cors: {allowHeaders: ["*"], allowMethods: ["GET", "POST", "OPTIONS"], allowOrigins: ["https://tailcall.run"]}
The issue is intended to test headers that put automatically for `tailcall.run` and therefore we don't need to specify headers in test - we need to test that it works without headers

2024-06-21 10:31 UTC, meskill commented on tests/execution/test-cors-tailcall-run.md
> +  example: String @http(path: "/example")
need to mock this request

2024-06-21 10:31 UTC, meskill commented on tests/execution/test-cors-tailcall-run.md
> +      access-control-allow-origin: https://tailcall.run
we use snapshots and not explicit `expected` definitions in tests. That should be removed and proper snapshots should be generated

2024-06-21 10:33 UTC, meskill commented
Closing for now since it requires additional work. Feel free to reopen this when it's ready. If you have any troubles with code/tooling please ask in our #contributors channel on Discord

2024-06-21 10:33 UTC, closed without merging