refactor(2665): send system message once in InferTypeName generation
tailcallhq/tailcall pull request #2676
Opened 2024-08-12 20:20 UTC by onyedikachi-david

**Summary:**  
Refactored the InferTypeName logic to optimize the system message handling. System messages are now sent only once during the type name generation process, and user messages are sent individually for each type, reducing redundant message transmission.

**Issue Reference(s):**  
Fixes #2556
/claim #2556

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [ ] I have performed a self-review of my code.
- [ ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

2024-08-13 08:00 UTC, tusharmath commented on src/cli/llm/wizard.rs
> +            .exec_chat(self.model.as_str(), request, None)
Don't change this API.

2024-08-13 17:33 UTC, laststylebender14 requested changes

2024-08-13 17:33 UTC, laststylebender14 commented on src/cli/llm/infer_type_name.rs
> +        system_messages: &[ChatMessage],
can remove `system_messages` if we are not using it.

2024-08-13 17:33 UTC, laststylebender14 commented on src/cli/llm/infer_type_name.rs
> +        self.wizard.as_ref().unwrap().ask(question.clone()).await
our goal was to send system message only once but question itself contains the system message.

2024-08-13 17:33 UTC, laststylebender14 commented on src/cli/llm/infer_type_name.rs
> +    wizard: Option<Wizard<Question, Answer>>,
why it's optional?

2024-08-14 13:32 UTC, tusharmath commented
Moving to draft to reduce noise and improve CI efficiency. Once you are ready just mark it as "ready to review". Feel free to give a shoutout on the #contributors channel on Discord if you want immediate attention.

2024-09-05 10:02 UTC, closed without merging