chore: fix http conformance tests
tailcallhq/tailcall pull request #2709
Opened 2024-08-15 15:45 UTC by laststylebender14

**Summary:**  
_Briefly describe the changes made in this PR._

**Issue Reference(s):**  
Fixes #... _(Replace "..." with the issue number)_

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [ ] I have performed a self-review of my code.
- [ ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

2024-08-22 10:20 UTC, meskill requested changes

2024-08-22 10:20 UTC, meskill commented on src/core/jit/snapshots/tailcall__core__jit__builder__tests__variables.snap
> +        alias: None,
let's add some test to validate that alias are set sometimes

2024-08-22 10:20 UTC, meskill commented on src/core/jit/synth/synth.rs
> +                            let field_name = child.alias.as_deref().unwrap_or(child.name.as_str());
can we add a method to Field to wrap this logic and reuse it?

2024-08-23 13:10 UTC, karatakis commented
@meskill, we can merge this. It fixes all JIT conformance test problems except introspection

2024-08-23 21:59 UTC, meskill approved these changes

2024-08-23 22:00 UTC, meskill commented
> @meskill, we can merge this. It fixes all JIT conformance test problems except introspection

I've updated the pr with additional fixes and code cleanup. Please, check those and merge the pr if it's ok. Most of the snapshots changes are related to args ordering fix or new field

2024-08-26 08:38 UTC, karatakis approved these changes
It's okay. The TODOs can be addressed later

2024-08-26 08:41 UTC, merged