feat: display an upgrade message for the CLI
tailcallhq/tailcall pull request #937
Opened 2024-01-13 20:00 UTC by neo773

This PR displays an upgrade message for the CLI if there's an update available

![image](https://github.com/tailcallhq/tailcall/assets/62795688/8f955439-0022-49c3-be5a-dc031347db5c)

**Issue Reference(s):**  
Fixes #930

**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

/claim #930

2024-01-14 10:43 UTC, neo773 commented
@tusharmath 
Could I get a review on this?

2024-01-14 12:40 UTC, tusharmath commented
This is a lot of code to maintain. Is there a crate for this? Posted this on reddit to get some help - https://www.reddit.com/r/rust/comments/196f0kr/crate_for_checking_if_a_newer_version_of_the/

2024-01-16 07:48 UTC, neo773 commented
@tusharmath Could I get a re-review on this?
I refactored the code use update-informer crate

2024-01-24 16:13 UTC, meskill requested changes

2024-01-24 16:13 UTC, meskill commented on src/cli/update_checker.rs
> +  let output = std::process::Command::new("npm").arg("ls").arg("--global").output();
use could actually install it locally to project and use it with `npx tailcall`.

I think we could validate some available env variables that set by npm and other package manager to figure out how program is ran.

2024-01-24 16:13 UTC, meskill commented on src/cli/update_checker.rs
> +    if result.to_str().unwrap().contains("homebrew") {
to_str could fail actually. Consider to not create panics

2024-01-24 16:13 UTC, meskill commented on src/cli/update_checker.rs
> +  };
```suggestion
  let Some(current_version) = option_env!("APP_VERSION") else {
      return;
  };
```

2024-01-24 16:49 UTC, neo773 commented
@meskill 
Pushed a new commit

2024-01-26 14:32 UTC, tusharmath commented on src/cli/tc.rs
> +  rt.spawn(update_checker::check_for_update());
I don't think we should need this.

2024-01-27 06:34 UTC, tusharmath commented
Getting the following error.

```
❯ APP_VERSION=0.5.0 cargo run -- check ./examples/jsonplaceholder.graphql
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/tushar/Documents/Projects/tailcall/cloudflare/Cargo.toml
workspace: /Users/tushar/Documents/Projects/tailcall/Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
     Running `target/debug/tailcall check ./examples/jsonplaceholder.graphql`
[2024-01-27T06:33:45Z INFO  tailcall::cli::file] File read: ./examples/jsonplaceholder.graphql ... ok
[2024-01-27T06:33:45Z INFO  tailcall::cli::tc] Config successfully validated
N + 1: 1

thread 'main' panicked at /Users/tushar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

2024-01-28 09:30 UTC, neo773 commented
@tusharmath 
Fixed
<img width="989" alt="4B1D2D1D-7CB1-498C-9DBB-8FC1A7BA180C" src="https://github.com/tailcallhq/tailcall/assets/62795688/7eefcf98-45a0-41dc-9463-68b485e6ebf6">

2024-01-30 06:38 UTC, tusharmath approved these changes

2024-01-30 22:01 UTC, meskill approved these changes

2024-01-30 22:18 UTC, merged